"""DAWO Generator agents - Content creation.

Generator agents create content for publication:
- Instagram captions and graphics
- B2B outreach drafts

All generators operate at the 'generate' tier (defaults to Sonnet for quality output).
"""

from .instagram_caption import (
    CaptionGenerator,
    CaptionGeneratorProtocol,
    LLMClientProtocol,
    CaptionRequest,
    CaptionResult,
)
from .orshot_graphics import (
    OrshotRenderer,
    OrshotRendererProtocol,
    UsageTrackerProtocol,
    UsageLimitExceeded,
    RenderRequest,
    RenderResult,
    ContentType,
    InstagramFormat,
    Dimensions,
    get_target_dimensions,
    validate_template_dimensions,
    select_template_for_content,
    is_template_for_content_type,
)
from .nano_banana import (
    NanoBananaGenerator,
    NanoBananaGeneratorProtocol,
    ImageGenerationRequest,
    ImageGenerationResult,
    ImageStyleType,
    ContentFormat,
    ImageQualityScorer,
    QualityAssessment,
    build_prompt,
    get_negative_prompt,
    get_brand_keywords,
)
from .compliance_rewrite import (
    ComplianceRewriteSuggester,
    ComplianceRewriteSuggesterProtocol,
    RewriteRequest,
    RewriteResult,
    RewriteSuggestion,
    apply_suggestion,
    apply_all_suggestions,
)
from .content_quality import (
    ContentQualityScorer,
    ContentQualityScorerProtocol,
    QualityScoreRequest,
    QualityScoreResult,
    ComponentScore,
    ContentType as QualityContentType,  # Aliased to avoid conflict with orshot ContentType
    AuthenticityResult,
    PlatformOptimizationResult,
    EngagementPrediction,
    DEFAULT_WEIGHTS,
    validate_weights,
)
from .auto_publish_tagger import (
    AutoPublishTagger,
    AutoPublishTaggerProtocol,
    AutoPublishStatisticsService,
    TaggingRequest,
    TaggingResult,
    EligibilityResult,
    ApprovalOutcome,
    AccuracyStats,
    AutoPublishConfig,
    AutoPublishConfigProtocol,
    AutoPublishTag,
    DEFAULT_THRESHOLD,
    ELIGIBLE_MESSAGE,
    REQUIRED_COMPLIANCE_STATUS,
)
from .asset_usage import (
    AssetUsageTracker,
    AssetUsageTrackerProtocol,
    AssetUsageRepository,
    AssetUsageRepositoryProtocol,
    UsageEvent,
    PerformanceMetrics,
    AssetUsageRecord,
    AssetPerformanceResult,
    AssetSuggestion,
    ArchiveRecord,
    Platform,
    AssetType as UsageAssetType,  # Aliased to avoid conflict with orshot ContentType
    AssetStatus,
    calculate_performance_score,
    calculate_overall_performance,
    PERFORMANCE_WEIGHTS,
    ASSET_FOLDERS,
)

__all__: list[str] = [
    # Instagram Caption Generator (Story 3.3)
    "CaptionGenerator",
    "CaptionGeneratorProtocol",
    "LLMClientProtocol",
    "CaptionRequest",
    "CaptionResult",
    # Orshot Graphics Generator (Story 3.4)
    "OrshotRenderer",
    "OrshotRendererProtocol",
    "UsageTrackerProtocol",
    "UsageLimitExceeded",
    "RenderRequest",
    "RenderResult",
    "ContentType",
    "InstagramFormat",
    "Dimensions",
    "get_target_dimensions",
    "validate_template_dimensions",
    "select_template_for_content",
    "is_template_for_content_type",
    # Nano Banana AI Image Generator (Story 3.5)
    "NanoBananaGenerator",
    "NanoBananaGeneratorProtocol",
    "ImageGenerationRequest",
    "ImageGenerationResult",
    "ImageStyleType",
    "ContentFormat",
    "ImageQualityScorer",
    "QualityAssessment",
    "build_prompt",
    "get_negative_prompt",
    "get_brand_keywords",
    # Compliance Rewrite Suggester (Story 3.6)
    "ComplianceRewriteSuggester",
    "ComplianceRewriteSuggesterProtocol",
    "RewriteRequest",
    "RewriteResult",
    "RewriteSuggestion",
    "apply_suggestion",
    "apply_all_suggestions",
    # Content Quality Scorer (Story 3.7)
    "ContentQualityScorer",
    "ContentQualityScorerProtocol",
    "QualityScoreRequest",
    "QualityScoreResult",
    "ComponentScore",
    "QualityContentType",
    "AuthenticityResult",
    "PlatformOptimizationResult",
    "EngagementPrediction",
    "DEFAULT_WEIGHTS",
    "validate_weights",
    # Auto-Publish Eligibility Tagger (Story 3.8)
    "AutoPublishTagger",
    "AutoPublishTaggerProtocol",
    "AutoPublishStatisticsService",
    "TaggingRequest",
    "TaggingResult",
    "EligibilityResult",
    "ApprovalOutcome",
    "AccuracyStats",
    "AutoPublishConfig",
    "AutoPublishConfigProtocol",
    "AutoPublishTag",
    "DEFAULT_THRESHOLD",
    "ELIGIBLE_MESSAGE",
    "REQUIRED_COMPLIANCE_STATUS",
    # Asset Usage Tracker (Story 3.9)
    "AssetUsageTracker",
    "AssetUsageTrackerProtocol",
    "AssetUsageRepository",
    "AssetUsageRepositoryProtocol",
    "UsageEvent",
    "PerformanceMetrics",
    "AssetUsageRecord",
    "AssetPerformanceResult",
    "AssetSuggestion",
    "ArchiveRecord",
    "Platform",
    "UsageAssetType",
    "AssetStatus",
    "calculate_performance_score",
    "calculate_overall_performance",
    "PERFORMANCE_WEIGHTS",
    "ASSET_FOLDERS",
]
